#!/bin/bash

# 🚀 Script de Deploy Manual - Emails StaFotos
# Como as Edge Functions já estão criadas localmente, você pode fazer o deploy pelo Supabase Dashboard

echo "============================================"
echo "📧 DEPLOY DE EMAILS - StaFotos"
echo "============================================"
echo ""
echo "✅ API Key: Já configurada!"
echo "✅ Functions: Criadas localmente"
echo ""
echo "⚠️  O Supabase CLI está tendo problemas de autenticação."
echo "Vamos usar o método alternativo (Dashboard):"
echo ""
echo "============================================"
echo "🎯 MÉTODO ALTERNATIVO (Mais Simples):"
echo "============================================"
echo ""
echo "1. Acesse: https://supabase.com/dashboard"
echo ""
echo "2. Selecione seu projeto StaFotos"
echo ""
echo "3. Vá em: Edge Functions (menu lateral)"
echo ""
echo "4. Clique em 'Create a new function'"
echo ""
echo "5. Para cada função, copie o código correspondente:"
echo ""
echo "   📁 supabase/functions/send-welcome-email/index.ts"
echo "   📁 supabase/functions/send-password-reset-email/index.ts"
echo "   📁 supabase/functions/send-sale-notification-email/index.ts"
echo "   📁 supabase/functions/send-purchase-confirmation-email/index.ts"
echo "   📁 supabase/functions/send-payout-approved-email/index.ts"
echo "   📁 supabase/functions/send-new-campaign-email/index.ts"
echo ""
echo "6. Cole o código no editor do Supabase"
echo ""
echo "7. Clique em 'Deploy function'"
echo ""
echo "8. Repita para todas as 6 funções"
echo ""
echo "============================================"
echo "✅ ALTERNATIVA MAIS RÁPIDA:"
echo "============================================"
echo ""
echo "Como o send-welcome-email já existe e está funcionando,"
echo "podemos ATUALIZAR apenas ele e criar as outras 5!"
echo ""
echo "Veja o arquivo: DEPLOY_INSTRUCTIONS.md para detalhes"
echo ""
echo "============================================"

